// Ghid pentru proprietari: „Utilizare platformă pentru rezervări” (tab în Contul meu > Informații).
// Conținut static; pagina îl afișează doar când funcția de rezervări e vizibilă.
"use strict";
const RO = [
  { icon: "📅", title: "Ce primești și cum funcționează", open: true, html: `
<p>Platforma îți pune la dispoziție un <strong>calendar de rezervări</strong> pentru proprietatea ta, un <strong>link de rezervare</strong> pe care îl poți trimite turiștilor și o <strong>aplicație pe telefon (OHT Host)</strong> cu care gestionezi totul fără să intri de fiecare dată în cont.</p>
<ul><li>Turistul alege datele, vede prețul final, își confirmă adresa de e-mail cu un cod și primește rezervarea confirmată. Tu primești e-mail și notificare.</li><li>Zilele rezervate se blochează automat în calendar, ca să nu ai suprapuneri.</li><li>Plata se face, deocamdată, <strong>direct la proprietate</strong>, fără comision. Plata online prin platformă va fi disponibilă în curând și o alegi tu, din secțiunea „Plată și reduceri”.</li><li>Ce poți face în aplicație: calendar, rezervări, camere libere, mesaj de sosire, notificări, acces pentru personal. <strong>Adăugarea cazării și a pozelor rămâne în cont.</strong></li></ul>
<p><strong>Important:</strong> rezervările se activează de către noi, pe fiecare cazare. Dacă nu vezi butonul „📅 Rezervări și calendar”, scrie-ne și le activăm.</p>` },
  { icon: "⚙️", title: "Prima configurare (o singură dată, din cont)", html: `
<ol><li>Din <a href="/cont">Proprietățile mele</a> apasă <strong>📅 Rezervări și calendar</strong> la cazarea ta. Ajungi pe <a href="/cont/rezervari">pagina de rezervări</a>.</li>
<li><strong>Preț de bază:</strong> prețul pe noapte, nopțile minime și numărul maxim de oaspeți. <strong>Prețurile din formularul cazării se preiau automat</strong> și rămân sincronizate: ce schimbi aici (sau în aplicația OHT Host, la Setări → Prețuri) se schimbă și pe pagina pensiunii, iar ce schimbi în formular se schimbă aici. Nu le completezi de două ori.</li>
<li><strong>Tarife speciale:</strong> alegi un șablon (weekend, Crăciun, Revelion, vară etc.) sau îți faci propriul interval, cu preț, nopți minime și zilele permise pentru sosire și plecare. Poți verifica oricând prețul unei perioade în secțiunea „Verifică prețul”.</li>
<li><strong>Camere:</strong> dacă închiriezi camere separat, le adaugi aici, cu capacitate și preț. Dacă nu adaugi nicio cameră, toată proprietatea se rezervă ca o singură unitate. Dacă închiriezi și toată pensiunea, poți seta o <strong>reducere</strong> pentru închirierea integrală.</li>
<li><strong>Sincronizare cu alte platforme (iCal):</strong> la fiecare platformă (Booking, Airbnb etc.) copiezi <em>linkul lor iCal</em> și îl lipești la noi, iar <em>linkul nostru</em> îl lipești la ei. Zilele ocupate se actualizează automat, la câteva minute, în ambele sensuri. Înainte de salvare poți apăsa „Previzualizare”.</li>
<li><strong>Rezervare instant:</strong> o pornești când ești pregătit. Alegi cât de repede poate rezerva turistul (aceeași zi, cu 1, 2, 3 sau 7 zile înainte). Apoi linkul de rezervare apare în pagină; îl poți trimite pe WhatsApp, pune pe Facebook sau în bio.</li></ol>` },
  { icon: "📲", title: "Cum instalezi aplicația OHT Host", html: `
<p>Aplicația se instalează direct din browser, fără magazin de aplicații. E gratuită și nu ocupă aproape deloc spațiu.</p>
<p><strong>Pe iPhone (Safari):</strong></p><ol><li>Deschide <a href="https://host.opening-hours-today.eu/gazda/">host.opening-hours-today.eu</a> în <strong>Safari</strong> (nu în Chrome).</li><li>Apasă butonul <strong>Partajează</strong> (pătratul cu săgeată în sus).</li><li>Alege <strong>Adaugă pe ecranul principal</strong> și apoi <strong>Adaugă</strong>.</li><li>Deschide aplicația <strong>OHT Host</strong> de pe ecranul principal.</li></ol>
<p><strong>Pe Android (Chrome):</strong></p><ol><li>Deschide <a href="https://host.opening-hours-today.eu/gazda/">host.opening-hours-today.eu</a> în Chrome.</li><li>Apasă butonul <strong>Instalează aplicația</strong> din pagină (sau meniul ⋮ → <strong>Instalează aplicația</strong>).</li><li>Deschide aplicația <strong>OHT Host</strong> de pe ecranul principal.</li></ol>
<p><strong>Pe calculator:</strong> nu e nevoie să instalezi nimic. Folosești pagina de rezervări din cont, în browser.</p>
<p>Ce vezi la prima deschidere: un ecran cu numele <strong>OHT Host</strong>. Dacă ești deja conectat în cont pe acel telefon, vezi două butoane pentru activarea intrării rapide. Dacă nu, vezi un câmp pentru <strong>cod</strong> (vezi mai jos).</p>` },
  { icon: "🔐", title: "Cum intri în aplicație: Face ID, amprentă sau PIN", html: `
<p>Nu ai nicio parolă de ținut minte și nu primești linkuri pe e-mail. Prima dată când deschizi aplicația, îți alegi cum vrei să intri, apoi o deschizi în două secunde.</p>
<p><strong>Ce alegi la prima deschidere:</strong></p>
<ul><li><strong>Face ID / amprentă:</strong> cea mai simplă. Merge dacă telefonul tău se deblochează cu fața sau cu amprenta. Dacă nu ești sigur că ai așa ceva pornit, verifici în <em>setările telefonului tău</em> (nu în aplicație), la „Securitate” sau „Face ID / Amprentă”.</li><li><strong>PIN de 6 cifre:</strong> pentru telefoanele fără Face ID sau amprentă, sau dacă preferi un cod. Alegi tu cifrele. Cifrele prea simple (111111, 123456) nu sunt acceptate.</li></ul>
<p><strong>Pas cu pas, dacă aplicația îți cere un cod:</strong></p>
<ol><li>Deschide pe telefon browserul (Safari sau Chrome) și intră în contul tău pe <a href="/cont">opening-hours-today.eu</a>, la <strong>Proprietățile mele</strong>.</li><li>La cazarea ta apasă <strong>📅 Rezervări și calendar</strong>.</li><li>Pe pagina care se deschide, în căsuța „Ai deja aplicația OHT Host pe ecranul principal și îți cere un cod?”, apasă butonul <strong>Generează cod</strong>.</li><li>Apare un cod de 8 litere și cifre. Ține minte codul sau lasă pagina deschisă.</li><li>Deschide aplicația <strong>OHT Host</strong>, scrie codul în câmpul de sus și apasă <strong>Activează cu PIN</strong>.</li><li>Alege un PIN de 6 cifre. Gata, data viitoare intri doar cu PIN-ul.</li></ol>
<p>Codul este valabil <strong>10 minute</strong> și se folosește o singură dată. Dacă a expirat, apeși din nou Generează cod.</p>
<p><strong>Vrei Face ID sau amprentă, după ce ai intrat cu PIN?</strong> În aplicație apeși jos <strong>Setări</strong>, cobori la <strong>Dispozitivele mele</strong> și apeși <strong>Adaugă Face ID pe acest telefon</strong>. La fel poți adăuga PIN dacă ai început cu Face ID.</p>
<p><strong>Ai greșit PIN-ul de 5 ori?</strong> Din siguranță, telefonul se blochează. Îl reactivezi simplu: generezi un cod nou (pașii de mai sus) și îți alegi un PIN nou.</p>
<p><strong>Pentru acțiunile importante</strong> (anulare, refuz, reținere din garanție, ștergerea unui telefon, schimbarea mesajului de sosire), aplicația îți cere încă o dată Face ID sau PIN-ul, dacă au trecut mai mult de 10 minute. Este doar o măsură de siguranță.</p>
<p><strong>Ți-ai pierdut telefonul?</strong> Ia alt telefon, deschide aplicația OHT Host (dacă nu o ai, o instalezi și generezi un cod, ca mai sus), apasă jos <strong>Setări</strong>, la <strong>Dispozitivele mele</strong> găsești telefonul vechi și apeși <strong>Șterge</strong>. De atunci nimeni nu mai poate intra cu el.</p>` },
  { icon: "📱", title: "Cele 4 ecrane ale aplicației", html: `
<p>Sus, dacă ai mai multe cazări, ai un <strong>selector</strong> cu care treci de la una la alta. Jos ai patru taburi:</p>
<ul><li><strong>Azi:</strong> câte camere sunt libere în seara asta, cu butoane pentru a închide/deschide azi sau mâine; sosiri azi și în următoarele 7 zile; cine e la tine acum; plecări; lucruri de rezolvat (rest de plată, sincronizare cu eroare, zile ocupate pe altă platformă). Pe fiecare rezervare ai butoane <em>Sună</em> și <em>WhatsApp</em>.</li><li><strong>Calendar:</strong> atingi zilele pe care vrei să le <strong>închizi</strong> (ex. renovare, ocupat fără rezervare) sau să le <strong>deschizi</strong>. Culori: gri = închis de tine, albastru = ocupat pe altă platformă, galben = rezervare în curs, verde = rezervat. Dacă ai camere, alegi mai întâi camera.</li><li><strong>Rezervări:</strong> lista rezervărilor viitoare, cu fișele de cazare completate din câte sunt necesare. Poți <strong>anula</strong>, <strong>refuza</strong> sau trimite manual mesajul cu <strong>accesul</strong>.</li><li><strong>Setări:</strong> rezervare instant, notificări, mesaj de sosire, acces pentru personal și dispozitivele tale.</li></ul>
<p>Prețurile detaliate, camerele și sincronizările iCal se editează din contul de pe site, la <em>Setări → Deschide în cont</em>.</p>` },
  { icon: "🔔", title: "Notificări și mesajul automat de sosire", html: `
<p><strong>Notificări:</strong> în <em>Setări → Notificări</em> apeși <strong>Activează notificările</strong> și accepți cererea telefonului. Pe iPhone merg doar după ce aplicația e adăugată pe ecranul principal (iOS 16.4 sau mai nou). Primești alertă la rezervare nouă, anulare, plată rămasă neîncasată și, în fiecare dimineață între 8 și 10, un <strong>rezumat</strong>: sosiri, plecări și rezervări apropiate cu fișe incomplete.</p>
<p><strong>Mesaj de sosire automat:</strong> în <em>Setări → Mesaj de sosire</em> scrii mesajul pentru oaspete și informațiile de acces (cod de la poartă, unde e cheia, ora de check-in). Alegi dacă pleacă cu 1 sau 2 zile înainte de sosire și îl pornești. Oaspetele îl primește <strong>pe e-mail</strong> chiar dacă fișa de cazare nu e completată încă (turistul o poate completa și la sosire, din linkul din mesaj). Dacă o plată online nu e încheiată, nu îl trimitem și te anunțăm pe tine, iar tu poți apăsa <strong>Trimite acces</strong> pe rezervare când vrei.</p>
<p>Mesajele pleacă între orele 9 și 21 și se trimit o singură dată.</p>` },
  { icon: "👥", title: "Acces pentru personal (recepție, familie)", html: `
<p>În <em>Setări → Personal</em> apeși <strong>Adaugă o persoană</strong>, îi dai un nume și, dacă ai mai multe cazări, alegi la care are acces. Primești un cod valabil 30 de minute. Persoana deschide <a href="https://host.opening-hours-today.eu/gazda/">host.opening-hours-today.eu</a> pe telefonul ei, scrie codul și își alege un PIN.</p>
<p>Ce poate face: vede calendarul și rezervările (nume, telefon, date), vede camerele libere și poate <strong>închide sau deschide zile</strong>. Ce nu poate face: nu vede sume sau tarife, nu anulează, nu refuză, nu schimbă setări, nu adaugă alte telefoane. Îi retragi accesul oricând din <em>Setări → Dispozitivele mele</em>.</p>` },
  { icon: "🧾", title: "Ce se întâmplă când vine o rezervare", html: `
<ol><li>Turistul alege datele pe pagina ta, vede prețul și își lasă datele. Zilele se blochează 10 minute cât își confirmă e-mailul cu un cod.</li><li>După confirmare, rezervarea apare la tine, ai notificare și e-mail, iar zilele sunt blocate în calendar.</li><li>Turistul primește un link unde își vede rezervarea și unde fiecare oaspete completează <strong>fișa de cazare</strong> (nume, date din act). Datele sunt criptate și le vezi doar tu, din cont.</li><li>Cu 1-2 zile înainte de sosire pleacă mesajul tău automat cu informațiile de acces (dacă l-ai pornit).</li><li>La final, datele din fișe se șterg automat după perioada de păstrare.</li></ol>
<p>Dacă ai deja rezervări pe alte platforme, ele apar în calendar prin sincronizarea iCal. Dacă o zi apare ocupată pe altă platformă dar e deja rezervată la tine, primești o alertă în <em>Azi</em>.</p>` },
  { icon: "❌", title: "Anulare și refuz", html: `
<ul><li><strong>Anulezi tu o rezervare:</strong> zilele se eliberează, turistul primește e-mail și, dacă plătise online, i se returnează suma integral.</li><li><strong>Refuzi un oaspete</strong> (fișă incompletă, date false, comportament neadecvat): alegi obligatoriu motivul și scrii un comentariu scurt. Rezervarea se anulează, turistul primește banii înapoi integral, iar refuzul se înregistrează. Refuzurile repetate sunt verificate de noi, ca să nu fie folosite pentru a evita rezervări legitime.</li><li><strong>Anulează turistul:</strong> zilele se eliberează automat și ești anunțat.</li></ul>
<p>La plata directă, banii nu trec prin platformă; înțelegerile despre avans sau rambursare rămân între tine și turist.</p>` },
  { icon: "🛡️", title: "Datele oaspeților", html: `
<ul><li>Datele din fișele de cazare sunt criptate. Numărul actului și CNP-ul (opțional) nu se păstrează în clar.</li><li>Le vezi doar tu, din cont, și fiecare deschidere este înregistrată.</li><li>Se șterg automat la <strong>90 de zile după plecare</strong> sau imediat la anularea rezervării.</li><li>Folosește datele doar pentru obligațiile tale legale de evidență a turiștilor și nu le trimite pe WhatsApp sau e-mail.</li></ul>` },
  { icon: "❓", title: "Probleme frecvente", html: `
<ul><li><strong>Nu văd butonul „Rezervări și calendar”:</strong> rezervările nu sunt activate pentru cazarea ta. Scrie-ne și le activăm.</li><li><strong>Aplicația nu mă recunoaște:</strong> dacă ai șters aplicația și ai reinstalat-o, activează din nou intrarea (din cont sau cu cod nou).</li><li><strong>Face ID nu apare:</strong> verifică iOS 16 sau mai nou, Safari actualizat și că Face ID e activat pe telefon. Altfel folosește PIN.</li><li><strong>Nu primesc notificări pe iPhone:</strong> aplicația trebuie adăugată pe ecranul principal, iar notificările permise din Setări → Notificări → OHT Host.</li><li><strong>Calendarul arată zile ocupate pe care nu le recunosc:</strong> vin din sincronizarea cu altă platformă (albastru). Se șterg singure când le eliberezi acolo.</li><li><strong>Un oaspete spune că nu poate rezerva:</strong> verifică nopțile minime, zilele permise pentru sosire/plecare și anticiparea minimă din Setări.</li></ul>
<p>Dacă ai nevoie de ajutor, scrie-ne pe <a href="/cont/contact">WhatsApp</a>.</p>` },
];

const EN = [
  { icon: "📅", title: "What you get and how it works", open: true, html: `
<p>The platform provides a <strong>booking calendar</strong> for your property, a <strong>booking link</strong> to send to guests and a <strong>phone app (Host)</strong> to manage everything without logging in each time.</p>
<ul><li>The guest picks dates, sees the final price, confirms their e-mail with a code and gets a confirmed booking. You get an e-mail and a notification.</li><li>Booked days are blocked automatically in the calendar, so you never get overlaps.</li><li>Payment is, for now, <strong>directly at the property</strong>, with no commission. Online payment through the platform is coming soon and you will choose it in the “Payment and discounts” section.</li><li>In the app you can: see the calendar, bookings and free rooms, set an arrival message, get notifications and give staff access. <strong>Adding the property and photos stays in your account.</strong></li></ul>
<p><strong>Note:</strong> bookings are enabled by us, per property. If you do not see the “📅 Bookings & calendar” button, write to us and we will enable it.</p>` },
  { icon: "⚙️", title: "First setup (once, from your account)", html: `
<ol><li>In <a href="/cont">My properties</a> press <strong>📅 Bookings & calendar</strong> on your property.</li><li>Set the <strong>base price</strong>, minimum nights and maximum guests.</li><li>Add <strong>special rates</strong> (weekends, holidays, season) with price, minimum nights and allowed check-in/check-out days. You can test any period under “Check price”.</li><li>Add <strong>rooms</strong> if you rent them separately; otherwise the whole property is one unit. You can set a discount for renting the whole property.</li><li><strong>Calendar sync (iCal):</strong> paste each platform's iCal link here, and paste ours there. Busy days update automatically in both directions.</li><li>Turn on <strong>instant booking</strong> when you are ready and choose how early guests can book. Then share your booking link.</li></ol>` },
  { icon: "📲", title: "How to install the Host app", html: `
<p><strong>iPhone (Safari):</strong> open <a href="https://host.opening-hours-today.eu/gazda/">host.opening-hours-today.eu</a> in Safari, tap <strong>Share</strong>, choose <strong>Add to Home Screen</strong>, then open <strong>OHT Host</strong> from your home screen.</p>
<p><strong>Android (Chrome):</strong> open the same address in Chrome, tap the <strong>Install app</strong> button (or menu ⋮ → <strong>Install app</strong>), then open <strong>OHT Host</strong>.</p>
<p>On a computer you do not need to install anything; use the bookings page in your account.</p>` },
  { icon: "🔐", title: "Signing in: Face ID, fingerprint or PIN", html: `
<p>No password to remember and no e-mail links. The first time you open the app you choose how to sign in.</p>
<ul><li><strong>Face ID / fingerprint:</strong> the easiest. It works if your phone unlocks with your face or fingerprint (check in your <em>phone's own settings</em>, under “Security” or “Face ID / Fingerprint”).</li><li><strong>6-digit PIN:</strong> for phones without Face ID or fingerprint, or if you prefer a code. Very simple PINs (111111, 123456) are refused.</li></ul>
<p><strong>If the app asks for a code:</strong></p>
<ol><li>On the phone, open your browser and sign in to your account at opening-hours-today.eu, under <strong>My properties</strong>.</li><li>Tap <strong>📅 Bookings & calendar</strong> on your property.</li><li>On the page that opens, in the box “Already have the OHT Host app on your home screen?”, tap <strong>Generate code</strong>.</li><li>Open the <strong>OHT Host</strong> app, type the 8-character code and tap <strong>Activate with PIN</strong>, then choose a 6-digit PIN.</li></ol>
<p>The code is valid for 10 minutes and works once. If it expired, tap Generate code again.</p>
<p><strong>Want Face ID or fingerprint later?</strong> In the app tap <strong>Settings</strong> at the bottom, scroll to <strong>My devices</strong> and tap <strong>Add Face ID on this phone</strong>.</p>
<p><strong>5 wrong PINs</strong> lock the phone for safety; generate a new code and choose a new PIN. <strong>Important actions</strong> (cancel, refuse, guarantee, deleting a phone) ask for Face ID / PIN again after 10 minutes.</p>
<p><strong>Lost your phone?</strong> On another phone open the OHT Host app (generate a code if needed), tap <strong>Settings → My devices</strong>, find the old phone and tap <strong>Delete</strong>.</p>` },
  { icon: "📱", title: "The 4 screens", html: `
<ul><li><strong>Today:</strong> free rooms tonight (with close/open buttons), arrivals, who is staying, departures and things to fix.</li><li><strong>Calendar:</strong> tap days to close or reopen them.</li><li><strong>Bookings:</strong> upcoming bookings; cancel, refuse or send the arrival info manually.</li><li><strong>Settings:</strong> instant booking, notifications, arrival message, staff access, devices.</li></ul>
<p>If you have several properties, use the switcher at the top. Detailed rates, rooms and iCal sync are edited from your account on the site.</p>` },
  { icon: "🔔", title: "Notifications and automatic arrival message", html: `
<p>Enable notifications in <em>Settings → Notifications</em> (on iPhone only after adding the app to the home screen, iOS 16.4+). You get alerts for new bookings, cancellations and failed payments, plus a morning summary between 8 and 10.</p>
<p>The <strong>arrival message</strong> (your note and access info such as a gate code) is e-mailed to the guest 1 or 2 days before arrival, even if the registration form is not completed yet (the guest can fill it in on arrival, from the link in the message). If an online payment is not settled it is not sent and you are notified and can press <strong>Send access</strong> yourself.</p>` },
  { icon: "👥", title: "Staff access", html: `
<p>In <em>Settings → Staff</em> add a person, pick the property, and give them the 30-minute code. They open <a href="https://host.opening-hours-today.eu/gazda/">host.opening-hours-today.eu</a>, enter the code and choose a PIN. They can see the calendar and bookings and close or open days; they cannot see amounts, cancel, refuse or change settings. Remove access anytime under <em>My devices</em>.</p>` },
  { icon: "🧾", title: "When a booking arrives", html: `
<p>The guest picks dates and confirms by e-mail code; days are held for 10 minutes. After confirmation the booking appears in your calendar and you are notified. Each guest fills in the registration form (stored encrypted, visible only to you, deleted automatically 90 days after check-out or on cancellation). Your arrival message goes out before check-in if enabled.</p>` },
  { icon: "❌", title: "Cancellation and refusal", html: `
<p>If you cancel, days are released and the guest is notified (and fully refunded if they paid online). To refuse a guest you must choose a reason and add a short comment; the guest is fully refunded and the refusal is logged. Repeated refusals are reviewed by us. With direct payment, money does not pass through the platform.</p>` },
  { icon: "❓", title: "Common problems", html: `
<ul><li>No “Bookings & calendar” button: bookings are not enabled for your property yet. Write to us.</li><li>App does not recognise me: re-activate sign-in (from your account or with a new code).</li><li>No Face ID option: needs iOS 16+, updated Safari and Face ID enabled; otherwise use a PIN.</li><li>No notifications on iPhone: add the app to the home screen and allow notifications in iOS Settings.</li></ul>
<p>Need help? Write to us on <a href="/cont/contact">WhatsApp</a>.</p>` },
];

module.exports = { guide: (lang) => (lang === "en" ? EN : RO) };
