// Ghid pentru proprietari: „Utilizare platformă pentru rezervări” (tab în Contul meu > Informații).
// Conținut static; pagina îl afișează doar când funcția de rezervări e vizibilă.
"use strict";
const RO = [
  { icon: "📅", title: "Ce primești și cum funcționează", open: true, html: `
<p>Platforma îți dă un <strong>calendar de rezervări</strong> pentru cazarea ta, un <strong>link de rezervare</strong> pe care îl poți trimite turiștilor și o <strong>aplicație pe telefon (Gazdă)</strong> cu care gestionezi totul fără să intri de fiecare dată în cont.</p>
<ul><li>Turistul alege datele, vede prețul final, își confirmă adresa de e-mail cu un cod și primește rezervarea confirmată. Tu primești e-mail și notificare.</li><li>Zilele rezervate se blochează automat în calendar, ca să nu ai suprapuneri.</li><li>Plata se face, deocamdată, <strong>direct la proprietate</strong>, fără comision. Plata online prin platformă va fi disponibilă în curând și o alegi tu, din Preferințe.</li><li>Ce poți face în aplicație: calendar, rezervări, camere libere, mesaj de sosire, notificări, acces pentru personal. <strong>Adăugarea cazării și a pozelor rămâne în cont.</strong></li></ul>
<p><strong>Important:</strong> rezervările se activează de către noi, pe fiecare cazare. Dacă nu vezi butonul „📅 Rezervări și calendar”, scrie-ne și le activăm.</p>` },
  { icon: "⚙️", title: "Prima configurare (o singură dată, din cont)", html: `
<ol><li>Din <a href="/cont">Proprietățile mele</a> apasă <strong>📅 Rezervări și calendar</strong> la cazarea ta. Ajungi pe <a href="/cont/rezervari">pagina de rezervări</a>.</li>
<li><strong>Preț de bază:</strong> prețul pe noapte, nopțile minime și numărul maxim de oaspeți.</li>
<li><strong>Tarife speciale:</strong> alegi un șablon (weekend, Crăciun, Revelion, vară etc.) sau îți faci propriul interval, cu preț, nopți minime și zilele permise pentru sosire și plecare. Poți verifica oricând prețul unei perioade în secțiunea „Verifică prețul”.</li>
<li><strong>Camere:</strong> dacă închiriezi camere separat, le adaugi aici, cu capacitate și preț. Dacă nu adaugi nicio cameră, toată proprietatea se rezervă ca o singură unitate. Dacă închiriezi și toată pensiunea, poți seta o <strong>reducere</strong> pentru închirierea integrală.</li>
<li><strong>Sincronizare cu alte platforme (iCal):</strong> la fiecare platformă (Booking, Airbnb etc.) copiezi <em>linkul lor iCal</em> și îl lipești la noi, iar <em>linkul nostru</em> îl lipești la ei. Zilele ocupate se actualizează automat, la câteva minute, în ambele sensuri. Înainte de salvare poți apăsa „Previzualizare”.</li>
<li><strong>Rezervare instant:</strong> o pornești când ești pregătit. Alegi cât de repede poate rezerva turistul (aceeași zi, cu 1, 2, 3 sau 7 zile înainte). Apoi linkul de rezervare apare în pagină; îl poți trimite pe WhatsApp, pune pe Facebook sau în bio.</li></ol>` },
  { icon: "📲", title: "Cum instalezi aplicația Gazdă", html: `
<p>Aplicația se instalează direct din browser, fără magazin de aplicații. E gratuită și nu ocupă aproape deloc spațiu.</p>
<p><strong>Pe iPhone (Safari):</strong></p><ol><li>Deschide <a href="/gazda/">opening-hours-today.eu/gazda/</a> în <strong>Safari</strong> (nu în Chrome).</li><li>Apasă butonul <strong>Partajează</strong> (pătratul cu săgeată în sus).</li><li>Alege <strong>Adaugă pe ecranul principal</strong> și apoi <strong>Adaugă</strong>.</li><li>Deschide aplicația <strong>Gazdă</strong> de pe ecranul principal.</li></ol>
<p><strong>Pe Android (Chrome):</strong></p><ol><li>Deschide <a href="/gazda/">opening-hours-today.eu/gazda/</a> în Chrome.</li><li>Apasă butonul verde <strong>Instalează acum</strong> din pagină (sau meniul ⋮ → <strong>Instalează aplicația</strong>).</li><li>Deschide aplicația <strong>Gazdă</strong> de pe ecranul principal.</li></ol>
<p><strong>Pe calculator:</strong> nu e nevoie să instalezi nimic. Folosești pagina de rezervări din cont, în browser.</p>
<p>Ce vezi la prima deschidere: un ecran cu numele <strong>Gazdă</strong>. Dacă ești deja conectat în cont pe acel telefon, vezi două butoane pentru activarea intrării rapide. Dacă nu, vezi un câmp pentru <strong>cod</strong> (vezi mai jos).</p>` },
  { icon: "🔐", title: "Cum intri în aplicație: Face ID, amprentă sau PIN", html: `
<p>Nu există parolă și nu primești linkuri pe e-mail. La prima activare alegi una din două metode. Poți schimba oricând din <strong>Setări → Dispozitivele mele</strong>.</p>
<ul><li><strong>Face ID / amprentă:</strong> cea mai simplă. Funcționează pe iPhone cu iOS 16 sau mai nou și pe telefoane Android cu amprentă sau deblocare facială. Ai nevoie de acest telefon deblocat cu biometrie.</li><li><strong>PIN de 6 cifre:</strong> pentru telefoane fără biometrie. PIN-urile prea simple (111111, 123456) sunt refuzate. După <strong>5 PIN-uri greșite</strong>, dispozitivul se blochează și îl reactivezi din cont.</li></ul>
<p><strong>Dacă ești conectat în cont pe telefon:</strong> deschizi aplicația și alegi metoda. Gata.</p>
<p><strong>Dacă aplicația instalată nu vede contul (frecvent pe iPhone):</strong> în cont, pe pagina de rezervări, apeși <strong>Generează cod</strong>. Scrii codul de 8 caractere în aplicație (valabil 10 minute, o singură dată) și îți alegi un PIN.</p>
<p><strong>Acțiunile sensibile</strong> (anulare, refuz, reținere din garanție, ștergerea unui dispozitiv, modificarea mesajului de sosire) îți cer încă o dată Face ID sau PIN-ul, dacă au trecut mai mult de 10 minute.</p>
<p><strong>Ți-ai pierdut telefonul?</strong> Intră în cont de pe alt telefon, deschide aplicația, mergi la <strong>Setări → Dispozitivele mele</strong> și șterge telefonul pierdut. Din acel moment nu mai poate intra.</p>` },
  { icon: "📱", title: "Cele 4 ecrane ale aplicației", html: `
<p>Sus, dacă ai mai multe cazări, ai un <strong>selector</strong> cu care treci de la una la alta. Jos ai patru taburi:</p>
<ul><li><strong>Azi:</strong> câte camere sunt libere în seara asta, cu butoane pentru a închide/deschide azi sau mâine; sosiri azi și în următoarele 7 zile; cine e la tine acum; plecări; lucruri de rezolvat (rest de plată, sincronizare cu eroare, zile ocupate pe altă platformă). Pe fiecare rezervare ai butoane <em>Sună</em> și <em>WhatsApp</em>.</li><li><strong>Calendar:</strong> atingi zilele pe care vrei să le <strong>închizi</strong> (ex. renovare, ocupat fără rezervare) sau să le <strong>deschizi</strong>. Culori: gri = închis de tine, albastru = ocupat pe altă platformă, galben = rezervare în curs, verde = rezervat. Dacă ai camere, alegi mai întâi camera.</li><li><strong>Rezervări:</strong> lista rezervărilor viitoare, cu fișele de cazare completate din câte sunt necesare. Poți <strong>anula</strong>, <strong>refuza</strong> sau trimite manual mesajul cu <strong>accesul</strong>.</li><li><strong>Setări:</strong> rezervare instant, notificări, mesaj de sosire, acces pentru personal și dispozitivele tale.</li></ul>
<p>Prețurile detaliate, camerele și sincronizările iCal se editează din contul de pe site, la <em>Setări → Deschide în cont</em>.</p>` },
  { icon: "🔔", title: "Notificări și mesajul automat de sosire", html: `
<p><strong>Notificări:</strong> în <em>Setări → Notificări</em> apeși <strong>Activează notificările</strong> și accepți cererea telefonului. Pe iPhone merg doar după ce aplicația e adăugată pe ecranul principal (iOS 16.4 sau mai nou). Primești alertă la rezervare nouă, anulare, plată rămasă neîncasată și, în fiecare dimineață între 8 și 10, un <strong>rezumat</strong>: sosiri, plecări și rezervări apropiate cu fișe incomplete.</p>
<p><strong>Mesaj de sosire automat:</strong> în <em>Setări → Mesaj de sosire</em> scrii mesajul pentru oaspete și informațiile de acces (cod de la poartă, unde e cheia, ora de check-in). Alegi dacă pleacă cu 1 sau 2 zile înainte de sosire și îl pornești. Oaspetele îl primește <strong>pe e-mail</strong> doar dacă fișa de cazare e completată pentru toți și plata e încheiată. Altfel te anunțăm pe tine, iar tu poți apăsa <strong>Trimite acces</strong> pe rezervare când vrei.</p>
<p>Mesajele pleacă între orele 9 și 21 și se trimit o singură dată.</p>` },
  { icon: "👥", title: "Acces pentru personal (recepție, familie)", html: `
<p>În <em>Setări → Personal</em> apeși <strong>Adaugă o persoană</strong>, îi dai un nume și, dacă ai mai multe cazări, alegi la care are acces. Primești un cod valabil 30 de minute. Persoana deschide <a href="/gazda/">opening-hours-today.eu/gazda/</a> pe telefonul ei, scrie codul și își alege un PIN.</p>
<p>Ce poate face: vede calendarul și rezervările (nume, telefon, date), vede camerele libere și poate <strong>închide sau deschide zile</strong>. Ce nu poate face: nu vede sume sau tarife, nu anulează, nu refuză, nu schimbă setări, nu adaugă alte telefoane. Îi retragi accesul oricând din <em>Setări → Dispozitivele mele</em>.</p>` },
  { icon: "🧾", title: "Ce se întâmplă când vine o rezervare", html: `
<ol><li>Turistul alege datele pe pagina ta, vede prețul și își lasă datele. Zilele se blochează 10 minute cât își confirmă e-mailul cu un cod.</li><li>După confirmare, rezervarea apare la tine, ai notificare și e-mail, iar zilele sunt blocate în calendar.</li><li>Turistul primește un link unde își vede rezervarea și unde fiecare oaspete completează <strong>fișa de cazare</strong> (nume, date din act). Datele sunt criptate și le vezi doar tu, din cont.</li><li>Cu 1-2 zile înainte de sosire pleacă mesajul tău automat cu informațiile de acces (dacă l-ai pornit).</li><li>La final, datele din fișe se șterg automat după perioada de păstrare.</li></ol>
<p>Dacă ai deja rezervări pe alte platforme, ele apar în calendar prin sincronizarea iCal. Dacă o zi apare ocupată pe altă platformă dar e deja rezervată la tine, primești o alertă în <em>Azi</em>.</p>` },
  { icon: "❌", title: "Anulare și refuz", html: `
<ul><li><strong>Anulezi tu o rezervare:</strong> zilele se eliberează, turistul primește e-mail și, dacă plătise online, i se returnează suma integral.</li><li><strong>Refuzi un oaspete</strong> (fișă incompletă, date false, comportament neadecvat): alegi obligatoriu motivul și scrii un comentariu scurt. Rezervarea se anulează, turistul primește banii înapoi integral, iar refuzul se înregistrează. Refuzurile repetate sunt verificate de noi, ca să nu fie folosite pentru a evita rezervări legitime.</li><li><strong>Anulează turistul:</strong> zilele se eliberează automat și ești anunțat.</li></ul>
<p>La plata directă, banii nu trec prin platformă; înțelegerile despre avans sau rambursare rămân între tine și turist.</p>` },
  { icon: "🛡️", title: "Datele oaspeților", html: `
<ul><li>Datele din fișele de cazare sunt criptate. Numărul actului și CNP-ul (opțional) nu se păstrează în clar.</li><li>Le vezi doar tu, din cont, și fiecare deschidere este înregistrată.</li><li>Se șterg automat la <strong>90 de zile după plecare</strong> sau imediat la anularea rezervării.</li><li>Folosește datele doar pentru obligațiile tale legale de evidență a turiștilor și nu le trimite pe WhatsApp sau e-mail.</li></ul>` },
  { icon: "❓", title: "Probleme frecvente", html: `
<ul><li><strong>Nu văd butonul „Rezervări și calendar”:</strong> rezervările nu sunt activate pentru cazarea ta. Scrie-ne și le activăm.</li><li><strong>Aplicația nu mă recunoaște:</strong> dacă ai șters aplicația și ai reinstalat-o, activează din nou intrarea (din cont sau cu cod nou).</li><li><strong>Face ID nu apare:</strong> verifică iOS 16 sau mai nou, Safari actualizat și că Face ID e activat pe telefon. Altfel folosește PIN.</li><li><strong>Nu primesc notificări pe iPhone:</strong> aplicația trebuie adăugată pe ecranul principal, iar notificările permise din Setări → Notificări → Gazdă.</li><li><strong>Calendarul arată zile ocupate pe care nu le recunosc:</strong> vin din sincronizarea cu altă platformă (albastru). Se șterg singure când le eliberezi acolo.</li><li><strong>Un oaspete spune că nu poate rezerva:</strong> verifică nopțile minime, zilele permise pentru sosire/plecare și anticiparea minimă din Setări.</li></ul>
<p>Dacă ai nevoie de ajutor, scrie-ne pe <a href="/cont/contact">WhatsApp</a>.</p>` },
];

const EN = [
  { icon: "📅", title: "What you get and how it works", open: true, html: `
<p>The platform gives you a <strong>booking calendar</strong> for your property, a <strong>booking link</strong> to send to guests and a <strong>phone app (Host)</strong> to manage everything without logging in each time.</p>
<ul><li>The guest picks dates, sees the final price, confirms their e-mail with a code and gets a confirmed booking. You get an e-mail and a notification.</li><li>Booked days are blocked automatically in the calendar, so you never get overlaps.</li><li>Payment is, for now, <strong>directly at the property</strong>, with no commission. Online payment through the platform is coming soon and you will choose it in Preferences.</li><li>In the app you can: see the calendar, bookings and free rooms, set an arrival message, get notifications and give staff access. <strong>Adding the property and photos stays in your account.</strong></li></ul>
<p><strong>Note:</strong> bookings are enabled by us, per property. If you do not see the “📅 Bookings & calendar” button, write to us and we will enable it.</p>` },
  { icon: "⚙️", title: "First setup (once, from your account)", html: `
<ol><li>In <a href="/cont">My properties</a> press <strong>📅 Bookings & calendar</strong> on your property.</li><li>Set the <strong>base price</strong>, minimum nights and maximum guests.</li><li>Add <strong>special rates</strong> (weekends, holidays, season) with price, minimum nights and allowed check-in/check-out days. You can test any period under “Check price”.</li><li>Add <strong>rooms</strong> if you rent them separately; otherwise the whole property is one unit. You can set a discount for renting the whole property.</li><li><strong>Calendar sync (iCal):</strong> paste each platform's iCal link here, and paste ours there. Busy days update automatically in both directions.</li><li>Turn on <strong>instant booking</strong> when you are ready and choose how early guests can book. Then share your booking link.</li></ol>` },
  { icon: "📲", title: "How to install the Host app", html: `
<p><strong>iPhone (Safari):</strong> open <a href="/gazda/">opening-hours-today.eu/gazda/</a> in Safari, tap <strong>Share</strong>, choose <strong>Add to Home Screen</strong>, then open <strong>Gazdă</strong> from your home screen.</p>
<p><strong>Android (Chrome):</strong> open the same address in Chrome, tap the green <strong>Install now</strong> button (or menu ⋮ → <strong>Install app</strong>), then open <strong>Gazdă</strong>.</p>
<p>On a computer you do not need to install anything; use the bookings page in your account.</p>` },
  { icon: "🔐", title: "Signing in: Face ID, fingerprint or PIN", html: `
<p>No password and no e-mail links. On first activation choose Face ID / fingerprint (iOS 16+ or Android with biometrics) or a 6-digit PIN. You can change it anytime in <strong>Settings → My devices</strong>.</p>
<ul><li>If you are signed in to your account on the phone, just open the app and pick a method.</li><li>If the installed app cannot see your account (common on iPhone), press <strong>Generate code</strong> on the bookings page in your account, type the 8-character code in the app (valid 10 minutes, single use) and choose a PIN.</li><li>After 5 wrong PINs the device is locked and must be re-activated.</li><li>Sensitive actions (cancel, refuse, guarantee, deleting a device) ask for Face ID / PIN again if more than 10 minutes have passed.</li><li>Lost your phone? From another device open the app → <strong>Settings → My devices</strong> → delete it.</li></ul>` },
  { icon: "📱", title: "The 4 screens", html: `
<ul><li><strong>Today:</strong> free rooms tonight (with close/open buttons), arrivals, who is staying, departures and things to fix.</li><li><strong>Calendar:</strong> tap days to close or reopen them.</li><li><strong>Bookings:</strong> upcoming bookings; cancel, refuse or send the arrival info manually.</li><li><strong>Settings:</strong> instant booking, notifications, arrival message, staff access, devices.</li></ul>
<p>If you have several properties, use the switcher at the top. Detailed rates, rooms and iCal sync are edited from your account on the site.</p>` },
  { icon: "🔔", title: "Notifications and automatic arrival message", html: `
<p>Enable notifications in <em>Settings → Notifications</em> (on iPhone only after adding the app to the home screen, iOS 16.4+). You get alerts for new bookings, cancellations and failed payments, plus a morning summary between 8 and 10.</p>
<p>The <strong>arrival message</strong> (your note and access info such as a gate code) is e-mailed to the guest 1 or 2 days before arrival, only if every guest completed the registration form and payment is settled. Otherwise you are notified and can press <strong>Send access</strong> yourself.</p>` },
  { icon: "👥", title: "Staff access", html: `
<p>In <em>Settings → Staff</em> add a person, pick the property, and give them the 30-minute code. They open <a href="/gazda/">opening-hours-today.eu/gazda/</a>, enter the code and choose a PIN. They can see the calendar and bookings and close or open days; they cannot see amounts, cancel, refuse or change settings. Remove access anytime under <em>My devices</em>.</p>` },
  { icon: "🧾", title: "When a booking arrives", html: `
<p>The guest picks dates and confirms by e-mail code; days are held for 10 minutes. After confirmation the booking appears in your calendar and you are notified. Each guest fills in the registration form (stored encrypted, visible only to you, deleted automatically 90 days after check-out or on cancellation). Your arrival message goes out before check-in if enabled.</p>` },
  { icon: "❌", title: "Cancellation and refusal", html: `
<p>If you cancel, days are released and the guest is notified (and fully refunded if they paid online). To refuse a guest you must choose a reason and add a short comment; the guest is fully refunded and the refusal is logged. Repeated refusals are reviewed by us. With direct payment, money does not pass through the platform.</p>` },
  { icon: "❓", title: "Common problems", html: `
<ul><li>No “Bookings & calendar” button: bookings are not enabled for your property yet. Write to us.</li><li>App does not recognise me: re-activate sign-in (from your account or with a new code).</li><li>No Face ID option: needs iOS 16+, updated Safari and Face ID enabled; otherwise use a PIN.</li><li>No notifications on iPhone: add the app to the home screen and allow notifications in iOS Settings.</li></ul>
<p>Need help? Write to us on <a href="/cont/contact">WhatsApp</a>.</p>` },
];

module.exports = { guide: (lang) => (lang === "en" ? EN : RO) };
