-- Belgia — INSERT-uri generate automat din server.js (BE_STORE_CONFIG + ATTRACTIONS.be)
-- Rulează DUPĂ schema.sql. Sigur de rulat de mai multe ori: ON CONFLICT (slug) DO NOTHING.

-- ============================================================
-- SECTIUNEA 1: MAGAZINE — Belgia
-- ============================================================

INSERT INTO locatii (nume_locatie, oras, tara, slug, tip) VALUES
  ('Colruyt', 'Brussels', 'Belgia', 'colruyt-brussels-be', 'store'),
  ('Colruyt', 'Antwerpen', 'Belgia', 'colruyt-antwerpen-be', 'store'),
  ('Colruyt', 'Gent', 'Belgia', 'colruyt-gent-be', 'store'),
  ('Colruyt', 'Charleroi', 'Belgia', 'colruyt-charleroi-be', 'store'),
  ('Colruyt', 'Liège', 'Belgia', 'colruyt-liege-be', 'store'),
  ('Colruyt', 'Brugge', 'Belgia', 'colruyt-brugge-be', 'store'),
  ('Colruyt', 'Namur', 'Belgia', 'colruyt-namur-be', 'store'),
  ('Colruyt', 'Leuven', 'Belgia', 'colruyt-leuven-be', 'store'),
  ('Colruyt', 'Mons', 'Belgia', 'colruyt-mons-be', 'store'),
  ('Colruyt', 'Aalst', 'Belgia', 'colruyt-aalst-be', 'store'),
  ('Delhaize', 'Brussels', 'Belgia', 'delhaize-brussels-be', 'store'),
  ('Delhaize', 'Antwerpen', 'Belgia', 'delhaize-antwerpen-be', 'store'),
  ('Delhaize', 'Gent', 'Belgia', 'delhaize-gent-be', 'store'),
  ('Delhaize', 'Charleroi', 'Belgia', 'delhaize-charleroi-be', 'store'),
  ('Delhaize', 'Liège', 'Belgia', 'delhaize-liege-be', 'store'),
  ('Delhaize', 'Brugge', 'Belgia', 'delhaize-brugge-be', 'store'),
  ('Delhaize', 'Namur', 'Belgia', 'delhaize-namur-be', 'store'),
  ('Delhaize', 'Leuven', 'Belgia', 'delhaize-leuven-be', 'store'),
  ('Delhaize', 'Mons', 'Belgia', 'delhaize-mons-be', 'store'),
  ('Delhaize', 'Aalst', 'Belgia', 'delhaize-aalst-be', 'store'),
  ('Carrefour', 'Brussels', 'Belgia', 'carrefour-brussels-be', 'store'),
  ('Carrefour', 'Antwerpen', 'Belgia', 'carrefour-antwerpen-be', 'store'),
  ('Carrefour', 'Gent', 'Belgia', 'carrefour-gent-be', 'store'),
  ('Carrefour', 'Charleroi', 'Belgia', 'carrefour-charleroi-be', 'store'),
  ('Carrefour', 'Liège', 'Belgia', 'carrefour-liege-be', 'store'),
  ('Carrefour', 'Brugge', 'Belgia', 'carrefour-brugge-be', 'store'),
  ('Carrefour', 'Namur', 'Belgia', 'carrefour-namur-be', 'store'),
  ('Carrefour', 'Leuven', 'Belgia', 'carrefour-leuven-be', 'store'),
  ('Carrefour', 'Mons', 'Belgia', 'carrefour-mons-be', 'store'),
  ('Carrefour', 'Aalst', 'Belgia', 'carrefour-aalst-be', 'store'),
  ('Aldi', 'Brussels', 'Belgia', 'aldi-brussels-be', 'store'),
  ('Aldi', 'Antwerpen', 'Belgia', 'aldi-antwerpen-be', 'store'),
  ('Aldi', 'Gent', 'Belgia', 'aldi-gent-be', 'store'),
  ('Aldi', 'Charleroi', 'Belgia', 'aldi-charleroi-be', 'store'),
  ('Aldi', 'Liège', 'Belgia', 'aldi-liege-be', 'store'),
  ('Aldi', 'Brugge', 'Belgia', 'aldi-brugge-be', 'store'),
  ('Aldi', 'Namur', 'Belgia', 'aldi-namur-be', 'store'),
  ('Aldi', 'Leuven', 'Belgia', 'aldi-leuven-be', 'store'),
  ('Aldi', 'Mons', 'Belgia', 'aldi-mons-be', 'store'),
  ('Aldi', 'Aalst', 'Belgia', 'aldi-aalst-be', 'store'),
  ('Lidl', 'Brussels', 'Belgia', 'lidl-brussels-be', 'store'),
  ('Lidl', 'Antwerpen', 'Belgia', 'lidl-antwerpen-be', 'store'),
  ('Lidl', 'Gent', 'Belgia', 'lidl-gent-be', 'store'),
  ('Lidl', 'Charleroi', 'Belgia', 'lidl-charleroi-be', 'store'),
  ('Lidl', 'Liège', 'Belgia', 'lidl-liege-be', 'store'),
  ('Lidl', 'Brugge', 'Belgia', 'lidl-brugge-be', 'store'),
  ('Lidl', 'Namur', 'Belgia', 'lidl-namur-be', 'store'),
  ('Lidl', 'Leuven', 'Belgia', 'lidl-leuven-be', 'store'),
  ('Lidl', 'Mons', 'Belgia', 'lidl-mons-be', 'store'),
  ('Lidl', 'Aalst', 'Belgia', 'lidl-aalst-be', 'store'),
  ('Spar', 'Brussels', 'Belgia', 'spar-brussels-be', 'store'),
  ('Spar', 'Antwerpen', 'Belgia', 'spar-antwerpen-be', 'store'),
  ('Spar', 'Gent', 'Belgia', 'spar-gent-be', 'store'),
  ('Spar', 'Charleroi', 'Belgia', 'spar-charleroi-be', 'store'),
  ('Spar', 'Liège', 'Belgia', 'spar-liege-be', 'store'),
  ('Spar', 'Brugge', 'Belgia', 'spar-brugge-be', 'store'),
  ('Spar', 'Namur', 'Belgia', 'spar-namur-be', 'store'),
  ('Spar', 'Leuven', 'Belgia', 'spar-leuven-be', 'store'),
  ('Spar', 'Mons', 'Belgia', 'spar-mons-be', 'store'),
  ('Spar', 'Aalst', 'Belgia', 'spar-aalst-be', 'store'),
  ('Intermarché', 'Brussels', 'Belgia', 'intermarche-brussels-be', 'store'),
  ('Intermarché', 'Antwerpen', 'Belgia', 'intermarche-antwerpen-be', 'store'),
  ('Intermarché', 'Gent', 'Belgia', 'intermarche-gent-be', 'store'),
  ('Intermarché', 'Charleroi', 'Belgia', 'intermarche-charleroi-be', 'store'),
  ('Intermarché', 'Liège', 'Belgia', 'intermarche-liege-be', 'store'),
  ('Intermarché', 'Brugge', 'Belgia', 'intermarche-brugge-be', 'store'),
  ('Intermarché', 'Namur', 'Belgia', 'intermarche-namur-be', 'store'),
  ('Intermarché', 'Leuven', 'Belgia', 'intermarche-leuven-be', 'store'),
  ('Intermarché', 'Mons', 'Belgia', 'intermarche-mons-be', 'store'),
  ('Intermarché', 'Aalst', 'Belgia', 'intermarche-aalst-be', 'store'),
  ('Cora', 'Brussels', 'Belgia', 'cora-brussels-be', 'store'),
  ('Cora', 'Antwerpen', 'Belgia', 'cora-antwerpen-be', 'store'),
  ('Cora', 'Gent', 'Belgia', 'cora-gent-be', 'store'),
  ('Cora', 'Charleroi', 'Belgia', 'cora-charleroi-be', 'store'),
  ('Cora', 'Liège', 'Belgia', 'cora-liege-be', 'store'),
  ('Cora', 'Brugge', 'Belgia', 'cora-brugge-be', 'store'),
  ('Cora', 'Namur', 'Belgia', 'cora-namur-be', 'store'),
  ('Cora', 'Leuven', 'Belgia', 'cora-leuven-be', 'store'),
  ('Cora', 'Mons', 'Belgia', 'cora-mons-be', 'store'),
  ('Cora', 'Aalst', 'Belgia', 'cora-aalst-be', 'store'),
  ('Match', 'Brussels', 'Belgia', 'match-brussels-be', 'store'),
  ('Match', 'Antwerpen', 'Belgia', 'match-antwerpen-be', 'store'),
  ('Match', 'Gent', 'Belgia', 'match-gent-be', 'store'),
  ('Match', 'Charleroi', 'Belgia', 'match-charleroi-be', 'store'),
  ('Match', 'Liège', 'Belgia', 'match-liege-be', 'store'),
  ('Match', 'Brugge', 'Belgia', 'match-brugge-be', 'store'),
  ('Match', 'Namur', 'Belgia', 'match-namur-be', 'store'),
  ('Match', 'Leuven', 'Belgia', 'match-leuven-be', 'store'),
  ('Match', 'Mons', 'Belgia', 'match-mons-be', 'store'),
  ('Match', 'Aalst', 'Belgia', 'match-aalst-be', 'store'),
  ('Okay', 'Brussels', 'Belgia', 'okay-brussels-be', 'store'),
  ('Okay', 'Antwerpen', 'Belgia', 'okay-antwerpen-be', 'store'),
  ('Okay', 'Gent', 'Belgia', 'okay-gent-be', 'store'),
  ('Okay', 'Charleroi', 'Belgia', 'okay-charleroi-be', 'store'),
  ('Okay', 'Liège', 'Belgia', 'okay-liege-be', 'store'),
  ('Okay', 'Brugge', 'Belgia', 'okay-brugge-be', 'store'),
  ('Okay', 'Namur', 'Belgia', 'okay-namur-be', 'store'),
  ('Okay', 'Leuven', 'Belgia', 'okay-leuven-be', 'store'),
  ('Okay', 'Mons', 'Belgia', 'okay-mons-be', 'store'),
  ('Okay', 'Aalst', 'Belgia', 'okay-aalst-be', 'store'),
  ('Proxy Delhaize', 'Brussels', 'Belgia', 'proxy-delhaize-brussels-be', 'store'),
  ('Proxy Delhaize', 'Antwerpen', 'Belgia', 'proxy-delhaize-antwerpen-be', 'store'),
  ('Proxy Delhaize', 'Gent', 'Belgia', 'proxy-delhaize-gent-be', 'store'),
  ('Proxy Delhaize', 'Charleroi', 'Belgia', 'proxy-delhaize-charleroi-be', 'store'),
  ('Proxy Delhaize', 'Liège', 'Belgia', 'proxy-delhaize-liege-be', 'store'),
  ('Proxy Delhaize', 'Brugge', 'Belgia', 'proxy-delhaize-brugge-be', 'store'),
  ('Proxy Delhaize', 'Namur', 'Belgia', 'proxy-delhaize-namur-be', 'store'),
  ('Proxy Delhaize', 'Leuven', 'Belgia', 'proxy-delhaize-leuven-be', 'store'),
  ('Proxy Delhaize', 'Mons', 'Belgia', 'proxy-delhaize-mons-be', 'store'),
  ('Proxy Delhaize', 'Aalst', 'Belgia', 'proxy-delhaize-aalst-be', 'store'),
  ('Alvo', 'Brussels', 'Belgia', 'alvo-brussels-be', 'store'),
  ('Alvo', 'Antwerpen', 'Belgia', 'alvo-antwerpen-be', 'store'),
  ('Alvo', 'Gent', 'Belgia', 'alvo-gent-be', 'store'),
  ('Alvo', 'Charleroi', 'Belgia', 'alvo-charleroi-be', 'store'),
  ('Alvo', 'Liège', 'Belgia', 'alvo-liege-be', 'store'),
  ('Alvo', 'Brugge', 'Belgia', 'alvo-brugge-be', 'store'),
  ('Alvo', 'Namur', 'Belgia', 'alvo-namur-be', 'store'),
  ('Alvo', 'Leuven', 'Belgia', 'alvo-leuven-be', 'store'),
  ('Alvo', 'Mons', 'Belgia', 'alvo-mons-be', 'store'),
  ('Alvo', 'Aalst', 'Belgia', 'alvo-aalst-be', 'store'),
  ('Brico', 'Brussels', 'Belgia', 'brico-brussels-be', 'store'),
  ('Brico', 'Antwerpen', 'Belgia', 'brico-antwerpen-be', 'store'),
  ('Brico', 'Gent', 'Belgia', 'brico-gent-be', 'store'),
  ('Brico', 'Charleroi', 'Belgia', 'brico-charleroi-be', 'store'),
  ('Brico', 'Liège', 'Belgia', 'brico-liege-be', 'store'),
  ('Brico', 'Brugge', 'Belgia', 'brico-brugge-be', 'store'),
  ('Brico', 'Namur', 'Belgia', 'brico-namur-be', 'store'),
  ('Brico', 'Leuven', 'Belgia', 'brico-leuven-be', 'store'),
  ('Brico', 'Mons', 'Belgia', 'brico-mons-be', 'store'),
  ('Brico', 'Aalst', 'Belgia', 'brico-aalst-be', 'store'),
  ('Gamma', 'Brussels', 'Belgia', 'gamma-brussels-be', 'store'),
  ('Gamma', 'Antwerpen', 'Belgia', 'gamma-antwerpen-be', 'store'),
  ('Gamma', 'Gent', 'Belgia', 'gamma-gent-be', 'store'),
  ('Gamma', 'Charleroi', 'Belgia', 'gamma-charleroi-be', 'store'),
  ('Gamma', 'Liège', 'Belgia', 'gamma-liege-be', 'store'),
  ('Gamma', 'Brugge', 'Belgia', 'gamma-brugge-be', 'store'),
  ('Gamma', 'Namur', 'Belgia', 'gamma-namur-be', 'store'),
  ('Gamma', 'Leuven', 'Belgia', 'gamma-leuven-be', 'store'),
  ('Gamma', 'Mons', 'Belgia', 'gamma-mons-be', 'store'),
  ('Gamma', 'Aalst', 'Belgia', 'gamma-aalst-be', 'store'),
  ('Hubo', 'Brussels', 'Belgia', 'hubo-brussels-be', 'store'),
  ('Hubo', 'Antwerpen', 'Belgia', 'hubo-antwerpen-be', 'store'),
  ('Hubo', 'Gent', 'Belgia', 'hubo-gent-be', 'store'),
  ('Hubo', 'Charleroi', 'Belgia', 'hubo-charleroi-be', 'store'),
  ('Hubo', 'Liège', 'Belgia', 'hubo-liege-be', 'store'),
  ('Hubo', 'Brugge', 'Belgia', 'hubo-brugge-be', 'store'),
  ('Hubo', 'Namur', 'Belgia', 'hubo-namur-be', 'store'),
  ('Hubo', 'Leuven', 'Belgia', 'hubo-leuven-be', 'store'),
  ('Hubo', 'Mons', 'Belgia', 'hubo-mons-be', 'store'),
  ('Hubo', 'Aalst', 'Belgia', 'hubo-aalst-be', 'store'),
  ('Ikea', 'Brussels', 'Belgia', 'ikea-brussels-be', 'store'),
  ('Ikea', 'Antwerpen', 'Belgia', 'ikea-antwerpen-be', 'store'),
  ('Ikea', 'Gent', 'Belgia', 'ikea-gent-be', 'store'),
  ('Ikea', 'Charleroi', 'Belgia', 'ikea-charleroi-be', 'store'),
  ('Ikea', 'Liège', 'Belgia', 'ikea-liege-be', 'store'),
  ('Ikea', 'Brugge', 'Belgia', 'ikea-brugge-be', 'store'),
  ('Ikea', 'Namur', 'Belgia', 'ikea-namur-be', 'store'),
  ('Ikea', 'Leuven', 'Belgia', 'ikea-leuven-be', 'store'),
  ('Ikea', 'Mons', 'Belgia', 'ikea-mons-be', 'store'),
  ('Ikea', 'Aalst', 'Belgia', 'ikea-aalst-be', 'store'),
  ('MediaMarkt', 'Brussels', 'Belgia', 'mediamarkt-brussels-be', 'store'),
  ('MediaMarkt', 'Antwerpen', 'Belgia', 'mediamarkt-antwerpen-be', 'store'),
  ('MediaMarkt', 'Gent', 'Belgia', 'mediamarkt-gent-be', 'store'),
  ('MediaMarkt', 'Charleroi', 'Belgia', 'mediamarkt-charleroi-be', 'store'),
  ('MediaMarkt', 'Liège', 'Belgia', 'mediamarkt-liege-be', 'store'),
  ('MediaMarkt', 'Brugge', 'Belgia', 'mediamarkt-brugge-be', 'store'),
  ('MediaMarkt', 'Namur', 'Belgia', 'mediamarkt-namur-be', 'store'),
  ('MediaMarkt', 'Leuven', 'Belgia', 'mediamarkt-leuven-be', 'store'),
  ('MediaMarkt', 'Mons', 'Belgia', 'mediamarkt-mons-be', 'store'),
  ('MediaMarkt', 'Aalst', 'Belgia', 'mediamarkt-aalst-be', 'store'),
  ('Krëfel', 'Brussels', 'Belgia', 'krefel-brussels-be', 'store'),
  ('Krëfel', 'Antwerpen', 'Belgia', 'krefel-antwerpen-be', 'store'),
  ('Krëfel', 'Gent', 'Belgia', 'krefel-gent-be', 'store'),
  ('Krëfel', 'Charleroi', 'Belgia', 'krefel-charleroi-be', 'store'),
  ('Krëfel', 'Liège', 'Belgia', 'krefel-liege-be', 'store'),
  ('Krëfel', 'Brugge', 'Belgia', 'krefel-brugge-be', 'store'),
  ('Krëfel', 'Namur', 'Belgia', 'krefel-namur-be', 'store'),
  ('Krëfel', 'Leuven', 'Belgia', 'krefel-leuven-be', 'store'),
  ('Krëfel', 'Mons', 'Belgia', 'krefel-mons-be', 'store'),
  ('Krëfel', 'Aalst', 'Belgia', 'krefel-aalst-be', 'store'),
  ('Vanden Borre', 'Brussels', 'Belgia', 'vanden-borre-brussels-be', 'store'),
  ('Vanden Borre', 'Antwerpen', 'Belgia', 'vanden-borre-antwerpen-be', 'store'),
  ('Vanden Borre', 'Gent', 'Belgia', 'vanden-borre-gent-be', 'store'),
  ('Vanden Borre', 'Charleroi', 'Belgia', 'vanden-borre-charleroi-be', 'store'),
  ('Vanden Borre', 'Liège', 'Belgia', 'vanden-borre-liege-be', 'store'),
  ('Vanden Borre', 'Brugge', 'Belgia', 'vanden-borre-brugge-be', 'store'),
  ('Vanden Borre', 'Namur', 'Belgia', 'vanden-borre-namur-be', 'store'),
  ('Vanden Borre', 'Leuven', 'Belgia', 'vanden-borre-leuven-be', 'store'),
  ('Vanden Borre', 'Mons', 'Belgia', 'vanden-borre-mons-be', 'store'),
  ('Vanden Borre', 'Aalst', 'Belgia', 'vanden-borre-aalst-be', 'store')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- SECTIUNEA 2: OBIECTIVE TURISTICE — Belgia (223 rânduri)
-- ============================================================

INSERT INTO locatii (nume_locatie, oras, tara, slug, tip) VALUES
  ('Palatul Regal din Bruxelles (Palais Royal)', '', 'Belgia', 'palatul-regal-din-bruxelles-palais-royal', 'attraction'),
  ('Palatul Națiunii (Palais de la Nation)', '', 'Belgia', 'palatul-natiunii-palais-de-la-nation', 'attraction'),
  ('Castelul Regal din Laeken (Château de Laeken)', '', 'Belgia', 'castelul-regal-din-laeken-chateau-de-laeken', 'attraction'),
  ('Palatul Egmont (Palais d''Egmont)', '', 'Belgia', 'palatul-egmont-palais-d-egmont', 'attraction'),
  ('Palacio de Charles de Lorraine', '', 'Belgia', 'palacio-de-charles-de-lorraine', 'attraction'),
  ('Castelul Rivieren', '', 'Belgia', 'castelul-rivieren', 'attraction'),
  ('Poarta Hal (Porte de Hal - Turn fortificat medieval)', '', 'Belgia', 'poarta-hal-porte-de-hal-turn-fortificat-medieval', 'attraction'),
  ('Turnul Negru (Tour Noire - Fragment de zid medieval)', '', 'Belgia', 'turnul-negru-tour-noire-fragment-de-zid-medieval', 'attraction'),
  ('Turnul de Televiziune din Bruxelles', '', 'Belgia', 'turnul-de-televiziune-din-bruxelles', 'attraction'),
  ('Catedrala Sfântul Mihail și Sfânta Gudula', '', 'Belgia', 'catedrala-sfantul-mihail-si-sfanta-gudula', 'attraction'),
  ('Bazilica Națională Sacré-Cœur din Koekelberg (A cincea ca mărime din lume)', '', 'Belgia', 'bazilica-nationala-sacre-c-ur-din-koekelberg-a-cincea-ca-marime-din-lume', 'attraction'),
  ('Biserica Notre-Dame du Sablon', '', 'Belgia', 'biserica-notre-dame-du-sablon', 'attraction'),
  ('Biserica Saint-Jacques-sur-Coudenberg', '', 'Belgia', 'biserica-saint-jacques-sur-coudenberg', 'attraction'),
  ('Biserica Notre-Dame de Laeken', '', 'Belgia', 'biserica-notre-dame-de-laeken', 'attraction'),
  ('Biserica Sainte-Catherine', '', 'Belgia', 'biserica-sainte-catherine', 'attraction'),
  ('Parcul din Bruxelles (Parc de Bruxelles)', '', 'Belgia', 'parcul-din-bruxelles-parc-de-bruxelles', 'attraction'),
  ('Parcul Cinquantenaire (Parc du Cinquantenaire)', '', 'Belgia', 'parcul-cinquantenaire-parc-du-cinquantenaire', 'attraction'),
  ('Parcul Leopold (Parc Léopold)', '', 'Belgia', 'parcul-leopold-parc-leopold', 'attraction'),
  ('Grădina Botanică Națională a Belgiei', '', 'Belgia', 'gradina-botanica-nationala-a-belgiei', 'attraction'),
  ('Pădurea Soignes (Forêt de Soignes - Fagi seculari UNESCO)', '', 'Belgia', 'padurea-soignes-foret-de-soignes-fagi-seculari-unesco', 'attraction'),
  ('Serele Regale din Laeken (Serres Royales)', '', 'Belgia', 'serele-regale-din-laeken-serres-royales', 'attraction'),
  ('Gara Centrală din Bruxelles (Bruxelles-Central)', '', 'Belgia', 'gara-centrala-din-bruxelles-bruxelles-central', 'attraction'),
  ('Gara de Sud (Bruxelles-Midi)', '', 'Belgia', 'gara-de-sud-bruxelles-midi', 'attraction'),
  ('Tunelul Leopold II (Infrastructură subterană majoră)', '', 'Belgia', 'tunelul-leopold-ii-infrastructura-subterana-majora', 'attraction'),
  ('Muzeele Regale de Arte Frumoase ale Belgiei', '', 'Belgia', 'muzeele-regale-de-arte-frumoase-ale-belgiei', 'attraction'),
  ('Muzeul Magritte', '', 'Belgia', 'muzeul-magritte', 'attraction'),
  ('Muzeul Instrumentelor Muzicale (MIM - Clădire Art Nouveau)', '', 'Belgia', 'muzeul-instrumentelor-muzicale-mim-cladire-art-nouveau', 'attraction'),
  ('Lumea Auto (AutoWorld Museum)', '', 'Belgia', 'lumea-auto-autoworld-museum', 'attraction'),
  ('Muzeul Regal al Armatei și de Istorie Militară', '', 'Belgia', 'muzeul-regal-al-armatei-si-de-istorie-militara', 'attraction'),
  ('Centrul Belgian al Benzilor Desenate (Comic Strip Center)', '', 'Belgia', 'centrul-belgian-al-benzilor-desenate-comic-strip-center', 'attraction'),
  ('Muzeul de Istorie Naturală (Institutul Regal)', '', 'Belgia', 'muzeul-de-istorie-naturala-institutul-regal', 'attraction'),
  ('Muzeul Orașului Bruxelles (Maison du Roi)', '', 'Belgia', 'muzeul-orasului-bruxelles-maison-du-roi', 'attraction'),
  ('Atomium (Simbolul arhitectural monumental)', '', 'Belgia', 'atomium-simbolul-arhitectural-monumental', 'attraction'),
  ('Piața Mare (Grand-Place / Grote Markt - UNESCO)', '', 'Belgia', 'piata-mare-grand-place-grote-markt-unesco', 'attraction'),
  ('Clădirea Primăriei (Hôtel de Ville)', '', 'Belgia', 'cladirea-primariei-hotel-de-ville', 'attraction'),
  ('Palatul de Justiție (Palais de Justice - Cea mai mare clădire din sec. XIX)', '', 'Belgia', 'palatul-de-justitie-palais-de-justice-cea-mai-mare-cladire-din-sec-xix', 'attraction'),
  ('Galeriile Regale Saint-Hubert (Printre primele galerii comerciale acoperite)', '', 'Belgia', 'galeriile-regale-saint-hubert-printre-primele-galerii-comerciale-acoperite', 'attraction'),
  ('Manneken Pis (Celebra statuie-simbol)', '', 'Belgia', 'manneken-pis-celebra-statuie-simbol', 'attraction'),
  ('Jeanneke Pis (Varianta feminină a statuii)', '', 'Belgia', 'jeanneke-pis-varianta-feminina-a-statuii', 'attraction'),
  ('Parcul Europa în Miniatură (Mini-Europe)', '', 'Belgia', 'parcul-europa-in-miniatura-mini-europe', 'attraction'),
  ('Arcul de Triumf din Parcul Cinquantenaire', '', 'Belgia', 'arcul-de-triumf-din-parcul-cinquantenaire', 'attraction'),
  ('Teatrul Regal de la Monnaie (La Monnaie)', '', 'Belgia', 'teatrul-regal-de-la-monnaie-la-monnaie', 'attraction'),
  ('Castelul Loppem', '', 'Belgia', 'castelul-loppem', 'attraction'),
  ('Castelul Wijnendale', '', 'Belgia', 'castelul-wijnendale', 'attraction'),
  ('Castelul Beauvoorde', '', 'Belgia', 'castelul-beauvoorde', 'attraction'),
  ('Castelul Male', '', 'Belgia', 'castelul-male', 'attraction'),
  ('Palatul Provincial (Provinciaal Hof)', '', 'Belgia', 'palatul-provincial-provinciaal-hof', 'attraction'),
  ('Castelul Tillegem', '', 'Belgia', 'castelul-tillegem', 'attraction'),
  ('Turnul cu Ceas din Bruges (Belfort - Simbolul medieval UNESCO)', '', 'Belgia', 'turnul-cu-ceas-din-bruges-belfort-simbolul-medieval-unesco', 'attraction'),
  ('Turnul Bisericii Maicii Domnului (Cel mai înalt turn de cărămidă)', '', 'Belgia', 'turnul-bisericii-maicii-domnului-cel-mai-inalt-turn-de-caramida', 'attraction'),
  ('Porțile Medievale ale Orașului (Gentpoort, Kruispoort, Smedenpoort)', 'Gent', 'Belgia', 'portile-medievale-ale-orasului-gentpoort-kruispoort-smedenpoort', 'attraction'),
  ('Turnul de Pulbere (Poertoren)', '', 'Belgia', 'turnul-de-pulbere-poertoren', 'attraction'),
  ('Bazilica Sângelui Sfânt (Heilig-Bloedbasiliek)', '', 'Belgia', 'bazilica-sangelui-sfant-heilig-bloedbasiliek', 'attraction'),
  ('Catedrala Sfântul Salvator (Sint-Salvatorskathedraal)', '', 'Belgia', 'catedrala-sfantul-salvator-sint-salvatorskathedraal', 'attraction'),
  ('Biserica Maicii Domnului (Onze-Lieve-Vrouwekerk - Statuia de Michelangelo)', '', 'Belgia', 'biserica-maicii-domnului-onze-lieve-vrouwekerk-statuia-de-michelangelo', 'attraction'),
  ('Mănăstirea Beguinage (Pridvorul de mănăstire prințesesc - UNESCO)', '', 'Belgia', 'manastirea-beguinage-pridvorul-de-manastire-printesesc-unesco', 'attraction'),
  ('Ierusalimkerk (Biserica Ierusalim)', '', 'Belgia', 'ierusalimkerk-biserica-ierusalim', 'attraction'),
  ('Abația Sfântul Andrei', '', 'Belgia', 'abatia-sfantul-andrei', 'attraction'),
  ('Lacul Iubirii (Minnewater și Parcul Minnewaterpark)', '', 'Belgia', 'lacul-iubirii-minnewater-si-parcul-minnewaterpark', 'attraction'),
  ('Rezervația Naturală Zwin (Zonă protejată de coastă pe mare)', '', 'Belgia', 'rezervatia-naturala-zwin-zona-protejata-de-coasta-pe-mare', 'attraction'),
  ('Canalele din Bruges (Canalele verzi și rețeaua acvatică)', '', 'Belgia', 'canalele-din-bruges-canalele-verzi-si-reteaua-acvatica', 'attraction'),
  ('Parcul Natural Het Zwin', '', 'Belgia', 'parcul-natural-het-zwin', 'attraction'),
  ('Plaja din Oostende', '', 'Belgia', 'plaja-din-oostende', 'attraction'),
  ('Podul Bonifacius (Ponte Bonifacio - Cel mai fotografiat pod romantic)', '', 'Belgia', 'podul-bonifacius-ponte-bonifacio-cel-mai-fotografiat-pod-romantic', 'attraction'),
  ('Portul Zeebrugge (Mare port maritim și terminal)', '', 'Belgia', 'portul-zeebrugge-mare-port-maritim-si-terminal', 'attraction'),
  ('Gara din Bruges (Station Brugge)', 'Brugge', 'Belgia', 'gara-din-bruges-station-brugge', 'attraction'),
  ('Debarcaderul istoric Rozenhoedkaai', '', 'Belgia', 'debarcaderul-istoric-rozenhoedkaai', 'attraction'),
  ('Muzeul Groeninge (Groeningemuseum - Pictorii Primitivi Flamanzi)', '', 'Belgia', 'muzeul-groeninge-groeningemuseum-pictorii-primitivi-flamanzi', 'attraction'),
  ('Spitalul Sfântul Ioan (Sint-Janshospitaal - Muzeul Memling)', '', 'Belgia', 'spitalul-sfantul-ioan-sint-janshospitaal-muzeul-memling', 'attraction'),
  ('Muzeul Ciocolatei (Choco-Story)', '', 'Belgia', 'muzeul-ciocolatei-choco-story', 'attraction'),
  ('Muzeul Cartofilor Prăjiți (Frietmuseum)', '', 'Belgia', 'muzeul-cartofilor-prajiti-frietmuseum', 'attraction'),
  ('Muzeul Chihlimbarului și Diamantelor', '', 'Belgia', 'muzeul-chihlimbarului-si-diamantelor', 'attraction'),
  ('Muzeul Istoric Historium Bruges', '', 'Belgia', 'muzeul-istoric-historium-bruges', 'attraction'),
  ('Piața Centrală din Bruges (Grote Markt)', '', 'Belgia', 'piata-centrala-din-bruges-grote-markt', 'attraction'),
  ('Piața Burg (Cu clădirile administrative istorice)', '', 'Belgia', 'piata-burg-cu-cladirile-administrative-istorice', 'attraction'),
  ('Clădirea Primăriei din Bruges (Stadhuis)', '', 'Belgia', 'cladirea-primariei-din-bruges-stadhuis', 'attraction'),
  ('Casele Breslelor Medievale', '', 'Belgia', 'casele-breslelor-medievale', 'attraction'),
  ('Vechea Hală de Pește (Vismarkt)', '', 'Belgia', 'vechea-hala-de-peste-vismarkt', 'attraction'),
  ('Clădirea Libertății din Bruges (Brugse Vrije)', '', 'Belgia', 'cladirea-libertatii-din-bruges-brugse-vrije', 'attraction'),
  ('Castelul Conților de Flandra (Gravensteen - Fortăreață medievală masivă)', '', 'Belgia', 'castelul-contilor-de-flandra-gravensteen-fortareata-medievala-masiva', 'attraction'),
  ('Castelul lui Gerald Diavolul (Geeraard de Duivelsteen)', '', 'Belgia', 'castelul-lui-gerald-diavolul-geeraard-de-duivelsteen', 'attraction'),
  ('Castelul Ooidonk', '', 'Belgia', 'castelul-ooidonk', 'attraction'),
  ('Castelul Laarne', '', 'Belgia', 'castelul-laarne', 'attraction'),
  ('Palatul de Justiție (Oude Justitiepaleis)', '', 'Belgia', 'palatul-de-justitie-oude-justitiepaleis', 'attraction'),
  ('Turnul cu Ceas din Gent (Belfort - Turnul independenței UNESCO)', 'Gent', 'Belgia', 'turnul-cu-ceas-din-gent-belfort-turnul-independentei-unesco', 'attraction'),
  ('Turnul Catedralei Sfântului Bavo', '', 'Belgia', 'turnul-catedralei-sfantului-bavo', 'attraction'),
  ('Zidurile Porții Rabot (Monument fortificat pe canal)', '', 'Belgia', 'zidurile-portii-rabot-monument-fortificat-pe-canal', 'attraction'),
  ('Catedrala Sfântul Bavo (Sint-Baafskathedraal - Altarul din Gent de Van Eyck)', 'Gent', 'Belgia', 'catedrala-sfantul-bavo-sint-baafskathedraal-altarul-din-gent-de-van-eyck', 'attraction'),
  ('Biserica Sfântul Nicolae (Sint-Niklaasker)', '', 'Belgia', 'biserica-sfantul-nicolae-sint-niklaasker', 'attraction'),
  ('Mănăstirea Sfântul Petru (Sint-Pietersabdij)', '', 'Belgia', 'manastirea-sfantul-petru-sint-pietersabdij', 'attraction'),
  ('Biserica Sfântul Mihail (Sint-Michielskerk)', '', 'Belgia', 'biserica-sfantul-mihail-sint-michielskerk', 'attraction'),
  ('Mănăstirea Beguinage Sfânta Elisabeta (Klein Begijnhof)', '', 'Belgia', 'manastirea-beguinage-sfanta-elisabeta-klein-begijnhof', 'attraction'),
  ('Ruinele Abației Sfântului Bavo', '', 'Belgia', 'ruinele-abatiei-sfantului-bavo', 'attraction'),
  ('Rezervația Naturală Bourgoyen-Ossemeersen', '', 'Belgia', 'rezervatia-naturala-bourgoyen-ossemeersen', 'attraction'),
  ('Parcul Citadelei (Citadelpark)', '', 'Belgia', 'parcul-citadelei-citadelpark', 'attraction'),
  ('Rețeaua de Canale Graslei și Korenlei', '', 'Belgia', 'reteaua-de-canale-graslei-si-korenlei', 'attraction'),
  ('Parcul Natural Blaarmeersen', '', 'Belgia', 'parcul-natural-blaarmeersen', 'attraction'),
  ('Podul Sfântul Mihail (Sint-Michielsbrug - Punct panoramic major)', '', 'Belgia', 'podul-sfantul-mihail-sint-michielsbrug-punct-panoramic-major', 'attraction'),
  ('Portul Comercial din Gent', 'Gent', 'Belgia', 'portul-comercial-din-gent', 'attraction'),
  ('Gara Gent-Sint-Pieters', 'Gent', 'Belgia', 'gara-gent-sint-pieters', 'attraction'),
  ('Muzeul de Arte Frumoase (MSK)', '', 'Belgia', 'muzeul-de-arte-frumoase-msk', 'attraction'),
  ('Muzeul de Artă Contemporană (S.M.A.K.)', '', 'Belgia', 'muzeul-de-arta-contemporana-s-m-a-k', 'attraction'),
  ('Muzeul de Industrie și Textile (Industriemuseum)', '', 'Belgia', 'muzeul-de-industrie-si-textile-industriemuseum', 'attraction'),
  ('STAM (Muzeul de Istorie al Orașului Gent)', 'Gent', 'Belgia', 'stam-muzeul-de-istorie-al-orasului-gent', 'attraction'),
  ('Muzeul de Etnografie și Folclor (Huis van Alijn)', '', 'Belgia', 'muzeul-de-etnografie-si-folclor-huis-van-alijn', 'attraction'),
  ('Faleza Graslei și Korenlei (Casele monumentale ale breslelor)', '', 'Belgia', 'faleza-graslei-si-korenlei-casele-monumentale-ale-breslelor', 'attraction'),
  ('Primăria din Gent (Stadhuis)', 'Gent', 'Belgia', 'primaria-din-gent-stadhuis', 'attraction'),
  ('Hala de Carne (Groot Vleeshuis)', '', 'Belgia', 'hala-de-carne-groot-vleeshuis', 'attraction'),
  ('Piața Vineri (Vrijdagmarkt)', '', 'Belgia', 'piata-vineri-vrijdagmarkt', 'attraction'),
  ('Hala Orașului (Stadshal - Arhitectură modernă)', '', 'Belgia', 'hala-orasului-stadshal-arhitectura-moderna', 'attraction'),
  ('Castelul Steen (Het Steen - Cetatea de pe malul râului Scheldt)', '', 'Belgia', 'castelul-steen-het-steen-cetatea-de-pe-malul-raului-scheldt', 'attraction'),
  ('Palatul Regal de pe Meir (Paleis op Meir)', '', 'Belgia', 'palatul-regal-de-pe-meir-paleis-op-meir', 'attraction'),
  ('Castelul Sterckshof', '', 'Belgia', 'castelul-sterckshof', 'attraction'),
  ('Palatul Bursei (Handelsbeurs)', '', 'Belgia', 'palatul-bursei-handelsbeurs', 'attraction'),
  ('Turnul Catedralei (Cel mai înalt turn de biserică din Benelux UNESCO)', '', 'Belgia', 'turnul-catedralei-cel-mai-inalt-turn-de-biserica-din-benelux-unesco', 'attraction'),
  ('Turnul Boerentoren (Primul zgârie-nori din Europa)', '', 'Belgia', 'turnul-boerentoren-primul-zgarie-nori-din-europa', 'attraction'),
  ('Fortăreața Lillo', '', 'Belgia', 'fortareata-lillo', 'attraction'),
  ('Catedrala Maicii Domnului (Onze-Lieve-Vrouwekathedraal - Picturi de Rubens)', '', 'Belgia', 'catedrala-maicii-domnului-onze-lieve-vrouwekathedraal-picturi-de-rubens', 'attraction'),
  ('Biserica Sfântul Carol Borromeo (Iezuită barocă superbă)', '', 'Belgia', 'biserica-sfantul-carol-borromeo-iezuita-baroca-superba', 'attraction'),
  ('Biserica Sfântul Iacob (Sint-Jacobskerk - Mormântul lui Rubens)', '', 'Belgia', 'biserica-sfantul-iacob-sint-jacobskerk-mormantul-lui-rubens', 'attraction'),
  ('Biserica Sfântul Pavel (Sint-Pauluskerk)', '', 'Belgia', 'biserica-sfantul-pavel-sint-pauluskerk', 'attraction'),
  ('Biserica Sfântul Andrei (Sint-Andrieskerk)', '', 'Belgia', 'biserica-sfantul-andrei-sint-andrieskerk', 'attraction'),
  ('Grădina Zoologică din Anvers (ZOO Antwerpen - Printre cele mai vechi)', 'Antwerpen', 'Belgia', 'gradina-zoologica-din-anvers-zoo-antwerpen-printre-cele-mai-vechi', 'attraction'),
  ('Parcul Middelheim (Parc monumental de sculpturi în aer liber)', '', 'Belgia', 'parcul-middelheim-parc-monumental-de-sculpturi-in-aer-liber', 'attraction'),
  ('Râul Scheldt și Faleza de mers', '', 'Belgia', 'raul-scheldt-si-faleza-de-mers', 'attraction'),
  ('Parcul Stadspark', '', 'Belgia', 'parcul-stadspark', 'attraction'),
  ('Gara Centrală din Anvers (Antwerpen-Centraal - Catedrala Gărilor)', 'Antwerpen', 'Belgia', 'gara-centrala-din-anvers-antwerpen-centraal-catedrala-garilor', 'attraction'),
  ('Tunelul Sfântul Ana (Tunel pietonal subteran istoric pe sub râu)', '', 'Belgia', 'tunelul-sfantul-ana-tunel-pietonal-subteran-istoric-pe-sub-rau', 'attraction'),
  ('Portul Anvers (Al doilea ca mărime din Europa)', '', 'Belgia', 'portul-anvers-al-doilea-ca-marime-din-europa', 'attraction'),
  ('Portul de iahturi Willemdok', '', 'Belgia', 'portul-de-iahturi-willemdok', 'attraction'),
  ('Casa Memorială Rubens (Rubenshuis)', '', 'Belgia', 'casa-memoriala-rubens-rubenshuis', 'attraction'),
  ('Muzeul MAS (Museum aan de Stroom - Clădire avangardistă)', '', 'Belgia', 'muzeul-mas-museum-aan-de-stroom-cladire-avangardista', 'attraction'),
  ('Muzeul Plantin-Moretus (Tipografie istorică unică UNESCO)', '', 'Belgia', 'muzeul-plantin-moretus-tipografie-istorica-unica-unesco', 'attraction'),
  ('Muzeul Regal de Arte Frumoase (KMSKA)', '', 'Belgia', 'muzeul-regal-de-arte-frumoase-kmska', 'attraction'),
  ('Muzeul Diamantelor (DIVA)', '', 'Belgia', 'muzeul-diamantelor-diva', 'attraction'),
  ('Muzeul Modei (MoMu)', '', 'Belgia', 'muzeul-modei-momu', 'attraction'),
  ('Muzeul Red Star Line (Istoria emigrației)', '', 'Belgia', 'muzeul-red-star-line-istoria-emigratiei', 'attraction'),
  ('Piața Mare din Anvers (Grote Markt și Fântâna Brabo)', '', 'Belgia', 'piata-mare-din-anvers-grote-markt-si-fantana-brabo', 'attraction'),
  ('Clădirea Primăriei (Stadhuis - Stil Renaștere UNESCO)', '', 'Belgia', 'cladirea-primariei-stadhuis-stil-renastere-unesco', 'attraction'),
  ('Bulevardul Comercial Meir', '', 'Belgia', 'bulevardul-comercial-meir', 'attraction'),
  ('Cartierul Diamantelor (Diamond Quarter)', '', 'Belgia', 'cartierul-diamantelor-diamond-quarter', 'attraction'),
  ('Teatrul Bourla (Bourlaschouwburg)', '', 'Belgia', 'teatrul-bourla-bourlaschouwburg', 'attraction'),
  ('Clădirea Tribunalului (Justitiepaleis - Acoperiș futurist)', '', 'Belgia', 'cladirea-tribunalului-justitiepaleis-acoperis-futurist', 'attraction'),
  ('Palatul Prinților-Episcopi din Liège', 'Liège', 'Belgia', 'palatul-printilor-episcopi-din-liege', 'attraction'),
  ('Castelul Modave', '', 'Belgia', 'castelul-modave', 'attraction'),
  ('Castelul Jehay', '', 'Belgia', 'castelul-jehay', 'attraction'),
  ('Castelul Corroy-le-Château', '', 'Belgia', 'castelul-corroy-le-chateau', 'attraction'),
  ('Palatul Episcopal din Tournai', '', 'Belgia', 'palatul-episcopal-din-tournai', 'attraction'),
  ('Castelul Beloeil (Versailles-ul Valoniei)', '', 'Belgia', 'castelul-beloeil-versailles-ul-valoniei', 'attraction'),
  ('Castelul Attre', '', 'Belgia', 'castelul-attre', 'attraction'),
  ('Citadela din Namur (Una dintre cele mai mari fortărețe din Europa)', 'Namur', 'Belgia', 'citadela-din-namur-una-dintre-cele-mai-mari-fortarete-din-europa', 'attraction'),
  ('Citadela din Liège', 'Liège', 'Belgia', 'citadela-din-liege', 'attraction'),
  ('Turnul cu Ceas din Tournai (Belfort - Cel mai vechi din Belgia UNESCO)', '', 'Belgia', 'turnul-cu-ceas-din-tournai-belfort-cel-mai-vechi-din-belgia-unesco', 'attraction'),
  ('Turnul de pază Tour de la Passerelle', '', 'Belgia', 'turnul-de-paza-tour-de-la-passerelle', 'attraction'),
  ('Fortul Flémalle', '', 'Belgia', 'fortul-flemalle', 'attraction'),
  ('Catedrala Sfântul Paul', '', 'Belgia', 'catedrala-sfantul-paul', 'attraction'),
  ('Catedrala Notre-Dame din Tournai (UNESCO - 5 turnuri monumentale)', '', 'Belgia', 'catedrala-notre-dame-din-tournai-unesco-5-turnuri-monumentale', 'attraction'),
  ('Catedrala Sfântul Albin', '', 'Belgia', 'catedrala-sfantul-albin', 'attraction'),
  ('Biserica Saint-Jacques', '', 'Belgia', 'biserica-saint-jacques', 'attraction'),
  ('Biserica Colegiată Saint-Barthélemy (Faimosul bazin baptismal)', '', 'Belgia', 'biserica-colegiata-saint-barthelemy-faimosul-bazin-baptismal', 'attraction'),
  ('Mănăstirea Maredsous', '', 'Belgia', 'manastirea-maredsous', 'attraction'),
  ('Parcul Natural High Fens (Hautes Fagnes - Platou montan și mlaștini)', '', 'Belgia', 'parcul-natural-high-fens-hautes-fagnes-platou-montan-si-mlastini', 'attraction'),
  ('Peșterile din Remouchamps (Cel mai lung traseu navigabil subteran)', '', 'Belgia', 'pesterile-din-remouchamps-cel-mai-lung-traseu-navigabil-subteran', 'attraction'),
  ('Muntele Bueren (Scara monumentală cu 374 de trepte)', '', 'Belgia', 'muntele-bueren-scara-monumentala-cu-374-de-trepte', 'attraction'),
  ('Parcul Natural din Văile Burdinale și Mehaigne', '', 'Belgia', 'parcul-natural-din-vaile-burdinale-si-mehaigne', 'attraction'),
  ('Parcul Natural al Văii Attert', '', 'Belgia', 'parcul-natural-al-vaii-attert', 'attraction'),
  ('Gara Liège-Guillemins (Capodoperă futuristă de Santiago Calatrava)', 'Liège', 'Belgia', 'gara-liege-guillemins-capodopera-futurista-de-santiago-calatrava', 'attraction'),
  ('Șoseaua panoramică de pe malul fluviului Meuse', '', 'Belgia', 'soseaua-panoramica-de-pe-malul-fluviului-meuse', 'attraction'),
  ('Podul Albert I', '', 'Belgia', 'podul-albert-i', 'attraction'),
  ('Podul de la Fragnée', '', 'Belgia', 'podul-de-la-fragnee', 'attraction'),
  ('Telecabina din Namur', 'Namur', 'Belgia', 'telecabina-din-namur', 'attraction'),
  ('Muzeul Curtius (Grand Curtius - Complex muzeal major)', '', 'Belgia', 'muzeul-curtius-grand-curtius-complex-muzeal-major', 'attraction'),
  ('Muzeul de Artă Valonă (La Boverie)', '', 'Belgia', 'muzeul-de-arta-valona-la-boverie', 'attraction'),
  ('Muzeul de Istorie și Arheologie', '', 'Belgia', 'muzeul-de-istorie-si-arheologie', 'attraction'),
  ('Muzeul de Arte Frumoase din Tournai (Clădire de Victor Horta)', '', 'Belgia', 'muzeul-de-arte-frumoase-din-tournai-cladire-de-victor-horta', 'attraction'),
  ('Situl Industrial Istoric Grand-Hornu (UNESCO)', '', 'Belgia', 'situl-industrial-istoric-grand-hornu-unesco', 'attraction'),
  ('Piața Saint-Lambert', '', 'Belgia', 'piata-saint-lambert', 'attraction'),
  ('Piața Mare din Tournai (Grand-Place)', '', 'Belgia', 'piata-mare-din-tournai-grand-place', 'attraction'),
  ('Piața Armelor (Place d''Armes)', '', 'Belgia', 'piata-armelor-place-d-armes', 'attraction'),
  ('Teatrul Regal din Liège (Opéra Royal de Wallonie)', 'Liège', 'Belgia', 'teatrul-regal-din-liege-opera-royal-de-wallonie', 'attraction'),
  ('Monumentul Perron (Simbolul libertății orașului)', '', 'Belgia', 'monumentul-perron-simbolul-libertatii-orasului', 'attraction'),
  ('Castelul Bouillon (Fortăreața medievală a lui Godfrey de Bouillon)', '', 'Belgia', 'castelul-bouillon-fortareata-medievala-a-lui-godfrey-de-bouillon', 'attraction'),
  ('Castelul Vêves (Castelul de basm cu turnuri ascuțite)', '', 'Belgia', 'castelul-veves-castelul-de-basm-cu-turnuri-ascutite', 'attraction'),
  ('Castelul Walzin (Ridicată dramatic pe o stâncă verticală deasupra râului)', '', 'Belgia', 'castelul-walzin-ridicata-dramatic-pe-o-stanca-verticala-deasupra-raului', 'attraction'),
  ('Castelul Lavaux-Sainte-Anne', '', 'Belgia', 'castelul-lavaux-sainte-anne', 'attraction'),
  ('Castelul Freÿr (Și grădinile sale în stil Versailles)', '', 'Belgia', 'castelul-freyr-si-gradinile-sale-in-stil-versailles', 'attraction'),
  ('Castelul Spontin', '', 'Belgia', 'castelul-spontin', 'attraction'),
  ('Citadela din Dinant (Ridicată pe stânca verticală simbol)', '', 'Belgia', 'citadela-din-dinant-ridicata-pe-stanca-verticala-simbol', 'attraction'),
  ('Turnul istoric Tour de la Monnaie', '', 'Belgia', 'turnul-istoric-tour-de-la-monnaie', 'attraction'),
  ('Fortul Rochefort', '', 'Belgia', 'fortul-rochefort', 'attraction'),
  ('Biserica Colegiată Notre-Dame de Dinant (Cu domul sub formă de pară)', '', 'Belgia', 'biserica-colegiata-notre-dame-de-dinant-cu-domul-sub-forma-de-para', 'attraction'),
  ('Abația Orval (Renumită pentru berea trapistă și ruinele istorice)', '', 'Belgia', 'abatia-orval-renumita-pentru-berea-trapista-si-ruinele-istorice', 'attraction'),
  ('Biserica Saint-Hubert (Biserica Colegiată)', '', 'Belgia', 'biserica-saint-hubert-biserica-colegiata', 'attraction'),
  ('Mănăstirea Chevetogne', '', 'Belgia', 'manastirea-chevetogne', 'attraction'),
  ('Biserica Saint-Hadelin', '', 'Belgia', 'biserica-saint-hadelin', 'attraction'),
  ('Peșterile din Han-sur-Lesse (Grottes de Han - Complex subteran uriaș)', '', 'Belgia', 'pesterile-din-han-sur-lesse-grottes-de-han-complex-subteran-urias', 'attraction'),
  ('Peștera Lorette-Rochefort', '', 'Belgia', 'pestera-lorette-rochefort', 'attraction'),
  ('Parcul Național din Valea Semois', '', 'Belgia', 'parcul-national-din-valea-semois', 'attraction'),
  ('Stânca Bayard (Rocher Bayard - Acul de piatră despicat)', '', 'Belgia', 'stanca-bayard-rocher-bayard-acul-de-piatra-despicat', 'attraction'),
  ('Izvoarele Termale din Spa (Orașul istoric fondator al conceptului SPA - UNESCO)', '', 'Belgia', 'izvoarele-termale-din-spa-orasul-istoric-fondator-al-conceptului-spa-unesco', 'attraction'),
  ('Parcul Natural al Celor Două Ourthes', '', 'Belgia', 'parcul-natural-al-celor-doua-ourthes', 'attraction'),
  ('Cascada Coo (Cea mai înaltă cascadă naturală din Belgia)', '', 'Belgia', 'cascada-coo-cea-mai-inalta-cascada-naturala-din-belgia', 'attraction'),
  ('Circuitul de Curse Spa-Francorchamps (Faimosul traseu de Formula 1)', '', 'Belgia', 'circuitul-de-curse-spa-francorchamps-faimosul-traseu-de-formula-1', 'attraction'),
  ('Șoseaua panoramică a Văii Semois', '', 'Belgia', 'soseaua-panoramica-a-vaii-semois', 'attraction'),
  ('Podul de pe râul Meuse', '', 'Belgia', 'podul-de-pe-raul-meuse', 'attraction'),
  ('Croazierele fluviale pe Meuse', '', 'Belgia', 'croazierele-fluviale-pe-meuse', 'attraction'),
  ('Casa Memorială Adolphe Sax (Inventatorul saxofonului)', '', 'Belgia', 'casa-memoriala-adolphe-sax-inventatorul-saxofonului', 'attraction'),
  ('Muzeul Abației din Stavelot', '', 'Belgia', 'muzeul-abatiei-din-stavelot', 'attraction'),
  ('Baza Arheologică a Castelului Bouillon', '', 'Belgia', 'baza-arheologica-a-castelului-bouillon', 'attraction'),
  ('Muzeul Circuitului Spa-Francorchamps', '', 'Belgia', 'muzeul-circuitului-spa-francorchamps', 'attraction'),
  ('Bulevardul de pe malul apei din Dinant (Cu saxofoane gigantice colorate)', '', 'Belgia', 'bulevardul-de-pe-malul-apei-din-dinant-cu-saxofoane-gigantice-colorate', 'attraction'),
  ('Piața Centrală din Spa', '', 'Belgia', 'piata-centrala-din-spa', 'attraction'),
  ('Piața Centrală din Bouillon', '', 'Belgia', 'piata-centrala-din-bouillon', 'attraction'),
  ('Walibi Belgium', '', 'Belgia', 'walibi-belgium', 'attraction'),
  ('Grădina Zoologică Pairi Daiza', '', 'Belgia', 'gradina-zoologica-pairi-daiza', 'attraction'),
  ('Plopsaland De Panne', '', 'Belgia', 'plopsaland-de-panne', 'attraction'),
  ('Aqualibi Belgium', '', 'Belgia', 'aqualibi-belgium', 'attraction'),
  ('Boudewijn Seapark Bruges', '', 'Belgia', 'boudewijn-seapark-bruges', 'attraction'),
  ('Plopsa Coo Stavelot', '', 'Belgia', 'plopsa-coo-stavelot', 'attraction'),
  ('Bellewaerde Ieper', '', 'Belgia', 'bellewaerde-ieper', 'attraction'),
  ('Muzeul Regal al Africii Centrale', '', 'Belgia', 'muzeul-regal-al-africii-centrale', 'attraction'),
  ('Centrul de Arte Frumoase BOZAR', '', 'Belgia', 'centrul-de-arte-frumoase-bozar', 'attraction'),
  ('Plopsaqua Hannut-Landen', '', 'Belgia', 'plopsaqua-hannut-landen', 'attraction')
ON CONFLICT (slug) DO NOTHING;
